SAR-9595 Implement back link
hmrc/minor-entity-identification-frontend pull request #92
Opened 2022-05-09 13:37 UTC by woollett-r

2022-05-09 15:52 UTC, refaque-ahmad requested changes
Guess it's worth adding test for backlink present in below views

1. OverseasCheckYourAnswersSpecificViewTests
2. TrustCheckYourAnswersSpecificViewTests
3. UaCheckYourAnswersSpecificViewTests

2022-05-10 08:29 UTC, woollett-r commented
I don't think we need to test for the backlink in the above files because the "SpecificView" tests focus on the summary lists in the check your answers pages. The background components such as the banner, title, submit button etc. are tested in the common view tests. I think the "Back" link can also be considered a background component and so the common view test is the right place for the backlink test.

2022-05-10 08:40 UTC, refaque-ahmad commented
Sorry missed that it's been added in testCheckYourAnswersCommonView, its all fine now :)

2022-05-10 10:18 UTC, refaque-ahmad approved these changes

2022-05-10 13:35 UTC, merged